# Use a lightweight version of Nginx based on Alpine
FROM nginx:alpine

# Copy the frontend files to the Nginx HTML directory
COPY ./ /usr/share/nginx/html/

# Expose port 80 (default for HTTP)
EXPOSE 80
