services:
  backend:
    image: todo-site-backend
    pull_policy: never
    container_name: todo-site-backend
    build:
      context: ./backend # Build context for the backend directory
      dockerfile: Dockerfile # Path to the Dockerfile
      target: runner
    ports:
      - "8000:8000" # Expose backend on port 8000
    env_file:
      - ./backend/.env

  frontend:
    image: todo-site-frontend
    pull_policy: never
    container_name: todo-site-frontend
    build:
      context: ./frontend # Build context for the frontend directory
      dockerfile: Dockerfile # Path to the Dockerfile
    ports:
      - "80:80" # Expose frontend on port 80

  mongodb:
    image: mongo:7.0.12
    container_name: todo-site-mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    container_name: todo-site-mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express/.env

volumes:
  mongodb-data:
