version: '3.8'

services:
  backend:
    build:
      context: ./backend # Build context for the backend directory
      dockerfile: Dockerfile # Path to the Dockerfile
    ports:
      - "8000:8000" # Expose backend on port 8000

  frontend:
    build:
      context: ./frontend # Build context for the frontend directory
      dockerfile: Dockerfile # Path to the Dockerfile
    ports:
      - "80:80" # Expose frontend on port 80
